### ISSUE TITLE
Sprite flicker Bug

### ISSUE THREAD

**Issue by ydwj** [BlackMATov/unity-iso-tools#1]
Adding another IsoObject to an IsoObject causes the Z-axis coordinates to switch violently, causing the Sprite to flash, and children of all IsoObject loaded objects cannot have other IsoObject

**Comment by BlackMATov** [comment]
Hello!

https://github.com/BlackMATov/unity-iso-tools#limitations

**Comment by ydwj** [comment]
OK，my bad ，ThankYou !

**Comment by BlackMATov** [comment]
No problem:-)
