### ISSUE TITLE
It doesnt work in custom axis  (0,1,0)

### ISSUE THREAD

**Issue by fumengame** [BlackMATov/unity-iso-tools#2]
hello ,my english is poor, sorry.
it only work in default transparency sort,and it doesnt work in my custom axis,

i use unity2021.3,i want to use isometic tilemap and this tools  together,the tools is so good and i dont want to give up it!!!!!

so can you give me some suggestions how to use the tool and sometic tilemap together,please...

**Comment by fumengame** [comment]
my english is poor ,if my word make you fell not happy，Please forgive me

**Comment by BlackMATov** [comment]
Hello! So, there are two ways to manage this:

- you can use "sorting layer" and "order in layers" for your tilemap layers to render them after or before IsoWorld;
- make a dedicated IsoObject for your tilemap grid to sort tilemap between another IsoObjects.

But you can't sort IsoObjects between separated tiles in tilemap. The tilemap will always be a single indivisible object.

I hope I was able to clarify this issue.

**Comment by fumengame** [comment]
> Hello! So, there are two ways to manage this:
> 
> * you can use "sorting layer" and "order in layers" for your tilemap layers to render them after or before IsoWorld;
> * make a dedicated IsoObject for your tilemap grid to sort tilemap between another IsoObjects.
> 
> But you can't sort IsoObjects between separated tiles in tilemap. The tilemap will always be a single indivisible object.
> 
> I hope I was able to clarify this issue.


hi,i unclear  describe the question,  if i use transparency sort in custom axis(0,1,0) ,the isoobject sprite rendering order has issue,such as the image.

else if i use defalut transparency sort ,isoojbect is right ,however tilemap rendering order has issue...

the two seems have conflict.

![微信图片_20240111145217](https://github.com/BlackMATov/unity-iso-tools/assets/23659182/cc2f4c63-75f4-488a-b5da-d1fe938d0c9d)
![微信图片_20240111145223](https://github.com/BlackMATov/unity-iso-tools/assets/23659182/cb733026-c13c-49dd-b3ba-d4c7c8fcf4cf)

**Comment by fumengame** [comment]
first image  is  custom axis(0,1,0)  ,isotoolset has issue. tilemap render order is right
second image is default transparency sort,tilemap render order has issue  ,isotoolset is right

**Comment by BlackMATov** [comment]
Yeah! I've got it. So, yes, right now IsoTools doesn't support custom transparency sort axis. But I'm going to think about this.

**Comment by fumengame** [comment]
> Yeah! I've got it. So, yes, right now IsoTools doesn't support custom transparency sort axis. But I'm going to think about this.

Looking forward to a solution，i think this is a FAQ for  some developers

**Comment by BlackMATov** [comment]
So, I thought about it. And, unfortunately, I can't place isometric objects correctly for custom sorting axis, because it just breaks my sorting method. Therefore, the toolset can deal with Z axis sorting only. Added this note to README.
