### ISSUE TITLE
Sorting issue in Scene05

### ISSUE THREAD

**Issue by helloghworld** [BlackMATov/unity-iso-tools#3]
@BlackMATov  Seems like the sorting for the moving cube is not correct. Check screenshot below:
<img width="255" alt="PixPin_2024-06-11_18-54-48" src="https://github.com/BlackMATov/unity-iso-tools/assets/13671271/cf0297d5-74aa-4536-928d-acd237962309">

**Comment by BlackMATov** [comment]
> @BlackMATov Seems like the sorting for the moving cube is not correct. Check screenshot below: <img alt="PixPin_2024-06-11_18-54-48" width="255" src="https://private-user-images.githubusercontent.com/13671271/338552938-cf0297d5-74aa-4536-928d-acd237962309.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMzA4NzksIm5iZiI6MTcxODEzMDU3OSwicGF0aCI6Ii8xMzY3MTI3MS8zMzg1NTI5MzgtY2YwMjk3ZDUtNzRhYS00NTM2LTkyOGQtYWNkMjM3OTYyMzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE4MjkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MDI5MGZlZjQ3NzZiN2YzZmM2ZGFkYjNhNDAxMTFiYzkwM2IzM2EzMTI1NjkwNDFlYzVmYTc4NzY5M2MyM2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gKMs1nvq_e2sCAMvUQ2-srAJHRNzqpatORTIpMysSX8">

Hello! Yes, it looks wrong, but if it happens outside the camera view it's ok. Objects are not sorted outside the camera to optimize the sorting process.

**Comment by BlackMATov** [comment]
Although I looked more closely. it still looks normal, in this demo scene this cube is moving which can be a little confusing. try playing with the scenes a little simpler :-)

**Comment by helloghworld** [comment]
@BlackMATov Today I double check the scene, it turns out the the blue cube's position z is higher than the moving cube. Thanks for your reply.
