### ISSUE TITLE
How to use the mouse to control the iso object to move following the mouse position.

### ISSUE THREAD

**Issue by fumengame** [BlackMATov/unity-iso-tools#4]
i dont want to move the iso object by changing ios postion
haha

**Comment by BlackMATov** [comment]
You should project a mouse screen position to an isometric position and change iso coords of your object.

You can use `MouseIsoPosition` function for example
https://github.com/BlackMATov/unity-iso-tools/blob/main/Assets/IsoTools/Docs/API.md
